import { Typography } from 'antd';

const { Title, Text } = Typography;

function UserAgreementModule() {
    return (
       <>
       <Title level={3}>WEBSITE USER AGREEMENT</Title>
       <Title level={5}>ACCEPTANCE OF TERMS</Title>
       <Text>ROBBO provides the following Terms of Service (“TOS”) to you, which we may update from time to time without notice to you. By accessing and using the ROBBO website, you accept and agree to be bound by the terms and provision of the TOS.</Text>
       <Title level={5}>DESCRIPTION OF ROBBO SERVICES</Title>
       <Text>Description of ROBBO Services: ROBBO provides supplemental science, technology, engineering, and math software and training classes for students enrolled in ROBBO Club courses including, but not limited to, curriculum and assessments, analytic tools, personalized content, and programming though its website and working with third party services. You understand and agree that ROBBO services may include advertisements and certain communications from ROBBO that you will not be able to opt out of, including but not limited to notifications about account activity, service announcements, administrative messages, and newsletters; these communications are considered part of your ROBBO membership. Unless explicitly stated otherwise, any new features that augment or enhance current ROBBO services shall be subject to the TOS. You understand that ROBBO services are provided “AS-IS” and that ROBBO assumes no responsibility for the timeliness, deletion, mis-delivery of information or data. You must provide and are responsible for all equipment necessary to access the ROBBO services. Most ROBBO Club classes and courses are delivered by independent third-parties—including but not limited to schools, individual teachers, retail stores, and entrepreneurs—who are not under the control of ROBBO. ROBBO assumes no responsibility for the actions of these individuals, and you agree to hold ROBBO harmless for third party actions in accordance with section 8 of the TOS. You understand that the technical processing and transmission of the ROBBO services may involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.</Text>
       <Title level={5}>YOUR REGISTRATION OBLIGATIONS</Title>
       <Text>In consideration of your use of the ROBBO services, you represent that you are of legal age to form a binding contract and are not a person barred from receiving ROBBO services under the laws of the Republic of Finland or other applicable jurisdiction. You also agree to: (a) provide true, accurate, current and complete information about yourself as prompted by the ROBBO registration form (the “Registration Data”) and (b) maintain and promptly update the Registration Data to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current or incomplete, or if ROBBO has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, ROBBO has the right to suspend or terminate your account and refuse any and all current or future use of the ROBBO services (or any portion thereof).</Text>
       <Title level={5}>ROBBO PRIVACY POLICY</Title>
       <Text>Registration Data and certain other information about you are subject to our applicable privacy policy. For more information, see You understand that through your use of ROBBO , you consent to the collection and use (as set forth in the applicable privacy policy) of this information, including the transfer of this information to the data storage, processing and use by ROBBO and its affiliates.</Text>
       <Title level={5}>CONTRIBUTIONS TO ROBBO</Title>
       <Text>By submitting ideas, suggestions, documents, and/or proposals (“Contributions”) to ROBBO , you acknowledge and agree that: (a) your Contributions do not contain confidential or proprietary information; (b) ROBBO is not under any obligation of confidentiality, express or implied, with respect to the Contributions; (c) ROBBO shall be entitled to use or disclose (or choose not to use or disclose) such Contributions for any purpose, in any way, in any media worldwide; (d) ROBBO may have something similar to the Contributions already under consideration or in development; (e) your Contributions automatically become the property of ROBBO without any obligation of ROBBO to you; and (f) you are not entitled to any compensation or reimbursement of any kind from ROBBO under any circumstances.</Text>
       <Title level={5}>INDEMNITY</Title>
       <Text>You agree to indemnify and hold ROBBO and its subsidiaries, affiliates, officers, agents, employees, partners and licensors harmless from any claim or demand, including reasonable attorneys’ fees, made by any third party due to or arising out of content you submit, post, transmit, modify or otherwise make available through the ROBBO website, your use of the ROBBO services, your connection to the ROBBO services, your violation of the TOS, or your violation of any rights of another. You agree to indemnify and hold ROBBO and its subsidiaries, affiliates, officers, agents, employees, partners and licensors harmless from any claim or demand, including reasonable attorneys’ fees, arising out of a dispute or claim against an independent third party—including but not limited to schools, individual teachers, retail stores, and entrepreneurs—for the third party’s actions or omissions.</Text>
       <Title level={5}>NO COMMERCIAL REUSE OF ROBBO</Title>
       <Text>You agree not to reproduce, duplicate, copy, sell, trade, resell or exploit for any commercial purposes, any portion or use of, or access to, ROBBO services (including but not limited to Content, Curriculum, Software, Analysis).</Text>
       <Title level={5}>GENERAL PRACTICES REGARDING USE AND STORAGE</Title>
       <Text>You acknowledge that ROBBO may establish general practices and limits concerning use of the ROBBO services, including without limitation the maximum number of days that data will be retained by ROBBO and the maximum number of times (and the maximum duration for which) you may access the ROBBO services in a given period of time. You agree that ROBBO has no responsibility or liability for the deletion or failure to store any content. You acknowledge that ROBBO reserves the right to log off accounts that are inactive for an extended period. You further acknowledge that ROBBO reserves the right to modify these general practices and limits from time to time.</Text>
       <Title level={5}>MODIFICATIONS TO ROBBO SERVICES</Title>
       <Text>ROBBO reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the ROBBO services (or any part thereof) with or without notice. You agree that ROBBO shall not be liable to you or to any third party for any modification, suspension or discontinuance of the ROBBO services (or any part thereof).</Text>
       <Title level={5}>LINKS</Title>
       <Text>ROBBO may provide, or third parties may provide, links to other World Wide Web sites or resources. You acknowledge and agree that ROBBO is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any content, advertising, products or other materials on or available from such sites or resources. You further acknowledge and agree that ROBBO shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such site or resource.</Text>
       <Title level={5}>ROBBO ’S PROPRIETARY RIGHTS</Title>
       <Text>You acknowledge and agree that the ROBBO services and any necessary software used in connection with the ROBBO services (“Software”) contain proprietary and confidential information that is protected by applicable intellectual property and other laws. You further acknowledge and agree that Content contained in advertisements or information presented to you through ROBBO or by advertisers is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. Except as expressly permitted by applicable law or as authorized by ROBBO or the applicable licensor (such as an advertiser), you agree not to modify, rent, lease, loan, sell, distribute, transmit, broadcast, publicly perform or create derivative works based on the ROBBO services, such Content or the Software, in whole or in part. ROBBO grants you a personal, non-transferable and non-exclusive right and license to use the object code of its Software on a single computer; provided that you do not (and do not allow any third party to) copy, modify, create a derivative work from, reverse engineer, reverse assemble or otherwise attempt to discover any source code, sell, assign, sublicense, grant a security interest in or otherwise transfer any right in the Software. You agree not to modify the Software in any manner or form, nor to use modified versions of the Software, including (without limitation) for the purpose of obtaining unauthorized access to the ROBBO website or services. You agree not to access ROBBO by any means other than through the interface that is provided by ROBBO for use in accessing its services.</Text>
       <Title level={5}>DISCLAIMER OF WARRANTIES YOU EXPRESSLY UNDERSTAND AND AGREE THAT:</Title>
       <Text>a. Your use of the ROBBO services and software are at your sole risk. The ROBBO services and software are provided on an “as is” and “as available” basis. ROBBO and its subsidiaries, affiliates, officers, employees, agents, partners and licensors expressly disclaim all warranties of any kind, whether express or implied, including, but not limited to the implied warranties of title, merchantability, fitness for a particular purpose and non-infringement.</Text>
       <br />
       <Text>b. ROBBO and its subsidiaries, affiliates, officers, employees, agents, partners and licensors make no warranty that (I) the ROBBO services or software will meet your requirements; (II) the ROBBO services or software will be uninterrupted, timely, secure or error-free; (III) the results that may be obtained from the use of the ROBBO services or software will be accurate or reliable; (IV) the quality of any products, services, information or other material purchased or obtained by you through the ROBBO services or software will meet your expectations; and (V) any errors in the software will be corrected.</Text>
       <br />
       <Text>c. ROBBO will not refund payments for any reason, including but not limited to missed classes, malfunction of software, and dissatisfaction with services.</Text>
       <br />
       <Text>d. Any material downloaded or otherwise obtained through the use of the ROBBO services or software is accessed at your own discretion and risk, and you will be solely responsible for and hereby waive any and all claims and causes of action with respect to any damage to your computer system, internet access, download or display device, or loss of data that results from the download of any such material.</Text>
       <br />
       <Text>e. no advice or information, whether oral or written, obtained by you from ROBBO or through or from ROBBO services or software shall create any warranty not expressly stated in the TOS.</Text>
       </>
    );
}

export default UserAgreementModule;